name: CatalogOps CD

on:
  workflow_run:
    workflows: ["CatalogOps CI"]
    types:
      - completed

  workflow_dispatch:
    inputs:
      version:
        description: "Docker image version to deploy (e.g. 1.7)"
        required: true
        type: string

jobs:
  docker:
    if: >
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.event == 'push') ||
      github.event_name == 'workflow_dispatch'

    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
          fetch-depth: 0

      - name: Get version
        id: version
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            VERSION="${{ inputs.version }}"
          else
            VERSION=$(git tag --list "v*" --sort=-version:refname | head -n 1)
            VERSION="${VERSION#v}"
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "Deploying version: ${VERSION:-latest}"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::469683586220:role/CatalogOps-GitHub-SSM-Role
          aws-region: us-east-1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: github.event_name != 'workflow_dispatch'
        run: |
          if [ -n "${{ steps.version.outputs.version }}" ]; then
            docker build \
              -t abhiabhishekoffl/catalogops:${{ steps.version.outputs.version }} \
              -t abhiabhishekoffl/catalogops:latest \
              .
          else
            docker build \
              -t abhiabhishekoffl/catalogops:latest \
              .
          fi

      - name: Push Docker image
        if: github.event_name != 'workflow_dispatch'
        run: |
          if [ -n "${{ steps.version.outputs.version }}" ]; then
            docker push abhiabhishekoffl/catalogops:${{ steps.version.outputs.version }}
          fi

          docker push abhiabhishekoffl/catalogops:latest

      - name: Deploy to EC2 via SSM
        run: |
          if [ -n "${{ steps.version.outputs.version }}" ]; then
            VERSION="${{ steps.version.outputs.version }}"
          else
            VERSION="latest"
          fi

          COMMAND_ID=$(aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=[
              "cd ~/catalogops",
              "export CATALOGOPS_VERSION='"$VERSION"'",
              "docker compose pull catalogops",
              "docker compose up -d catalogops",
              "docker image prune -f"
            ]' \
            --query "Command.CommandId" \
            --output text)

          echo "SSM Command ID: $COMMAND_ID"

          aws ssm wait command-executed \
            --command-id "$COMMAND_ID" \
            --instance-id "${{ secrets.EC2_INSTANCE_ID }}"

          echo "Deployment completed successfully."

      - name: Health check
        run: |
          curl --fail --retry 5 --retry-delay 5 --connect-timeout 10 http://${{ secrets.EC2_HOST }}/health