name: CatalogOps CD

on:
  workflow_run:
    workflows: ["CatalogOps CI"]
    types:
      - completed

  workflow_dispatch:

jobs:
  docker:
    if: >
      (github.event_name == 'workflow_run' &&
       github.event.workflow_run.conclusion == 'success' &&
       github.event.workflow_run.event == 'push') ||
      github.event_name == 'workflow_dispatch'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha || github.ref }}
          fetch-depth: 0

      - name: Get version tag
        id: version
        shell: bash
        run: |
          TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || true)

          if [[ "$TAG" == v* ]]; then
            VERSION="${TAG#v}"
          else
            VERSION=""
          fi

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          if [ -n "${{ steps.version.outputs.version }}" ]; then
            docker build \
              -t abhiabhishekoffl/catalogops:${{ steps.version.outputs.version }} \
              -t abhiabhishekoffl/catalogops:latest \
              .
          else
            docker build \
              -t abhiabhishekoffl/catalogops:latest \
              .
          fi

      - name: Push Docker image
        run: |
          if [ -n "${{ steps.version.outputs.version }}" ]; then
            docker push abhiabhishekoffl/catalogops:${{ steps.version.outputs.version }}
          fi

          docker push abhiabhishekoffl/catalogops:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/catalogops
            docker compose pull
            docker compose up -d
            docker image prune -f